name: food_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: 2.3.10
  flutter_screenutil: ^5.9.0
  animated_bottom_navigation_bar: ^1.3.3
  google_fonts: ^6.1.0
  chips_choice: ^3.0.1
  dio: ^5.4.3+1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

